In [1]:
!pip install torch

In [2]:
import torch
from tqdm.notebook import tqdm
import numpy as np
import pandas as pd

In [4]:
df = pd.read_csv('TextVsTopic.csv')


In [5]:
df

Unnamed: 0.1  Unnamed: 0  \
0                0           0   
1                1           1   
2                2           2   
3                3           3   
4                4           4   
...            ...         ...   
3669          3669        3669   
3670          3670        3670   
3671          3671        3671   
3672          3672        3672   
3673          3673        3673   

                                                   text              topic  
0     "Orange Is the New Black" star Yael Stone is r...        environment  
1     "We have one beautiful law," Trump recently sa...        gun-control  
2     ...immigrants as criminals and eugenics, all o...  white-nationalism  
3     ...we sounded the alarm in the early months of...  white-nationalism  
4     [Black Lives Matter] is essentially a non-fals...  marriage-equality  
...                                                 ...                ...  
3669  You’ve heard of Jim Crow and Southern Segregat...  marriage-equality  
3670  Young female athletes’ dreams and accomplishme...  marriage-equality  
3671  Young white men, reacting to social and educat...  white-nationalism  
3672  Young women taking part in high school and col...              sport  
3673  YouTube is making clear there will be no “birt...     elections-2020  

[3674 rows x 4 columns]

In [6]:
df.columns

Index(['Unnamed: 0.1', 'Unnamed: 0', 'text', 'topic'], dtype='object')

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3674 entries, 0 to 3673
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   Unnamed: 0.1  3674 non-null   int64 
 1   Unnamed: 0    3674 non-null   int64 
 2   text          3674 non-null   object
 3   topic         3674 non-null   object
dtypes: int64(2), object(2)
memory usage: 114.9+ KB


In [8]:
df.isnull().sum()

Unnamed: 0.1    0
Unnamed: 0      0
text            0
topic           0
dtype: int64

In [10]:
df.drop(['Unnamed: 0.1', 'Unnamed: 0'], axis = 1, inplace = True)

In [11]:
df.head()

text              topic
0  "Orange Is the New Black" star Yael Stone is r...        environment
1  "We have one beautiful law," Trump recently sa...        gun-control
2  ...immigrants as criminals and eugenics, all o...  white-nationalism
3  ...we sounded the alarm in the early months of...  white-nationalism
4  [Black Lives Matter] is essentially a non-fals...  marriage-equality

In [9]:
set(df.topic)

{'#metoo',
 'abortion',
 'black lives matter',
 'coronavirus',
 'elections-2020',
 'environment',
 'gender',
 'gun-control',
 'immigration',
 'international-politics-and-world-news',
 'islam',
 'marriage-equality',
 'middle-class',
 'sport',
 'student-debt',
 'taxes',
 'trump-presidency',
 'universal health care',
 'vaccines',
 'white-nationalism'}

In [12]:
df.topic.value_counts()

black lives matter                       436
vaccines                                 421
marriage-equality                        347
gun-control                              334
taxes                                    228
universal health care                    220
islam                                    207
environment                              135
white-nationalism                        131
gender                                   128
student-debt                             127
abortion                                 126
sport                                    126
immigration                              122
coronavirus                              121
trump-presidency                         120
middle-class                             117
elections-2020                           111
international-politics-and-world-news     88
#metoo                                    29
Name: topic, dtype: int64

In [13]:
df = df[df.topic.isin(['black lives matter', 'vaccines', 'marriage-equality', 'gun-control', 'islam', 'coronavirus'])] #change

In [14]:
df

text              topic
1     "We have one beautiful law," Trump recently sa...        gun-control
4     [Black Lives Matter] is essentially a non-fals...  marriage-equality
5     [Democrats employ] their full arsenal to deleg...           vaccines
6     [Newsoms's] obsession with masks has created a...           vaccines
7     [Newsoms's] onslaught of propaganda ignores co...           vaccines
...                                                 ...                ...
3666  You may remember that hours after America was ...              islam
3667  You may remember that NBC journalist Nancy Sny...           vaccines
3668  You need to keep a close eye on what your scho...  marriage-equality
3669  You’ve heard of Jim Crow and Southern Segregat...  marriage-equality
3670  Young female athletes’ dreams and accomplishme...  marriage-equality

[1866 rows x 2 columns]

In [15]:
df.topic.value_counts() #change

black lives matter    436
vaccines              421
marriage-equality     347
gun-control           334
islam                 207
coronavirus           121
Name: topic, dtype: int64

In [16]:
possible_labels = df.topic.unique()

In [17]:
possible_labels

array(['gun-control', 'marriage-equality', 'vaccines',
       'black lives matter', 'islam', 'coronavirus'], dtype=object)

In [18]:
label_dict = {}
for index, possible_label in enumerate(possible_labels):
    label_dict[possible_label] = index

In [19]:
label_dict

{'gun-control': 0,
 'marriage-equality': 1,
 'vaccines': 2,
 'black lives matter': 3,
 'islam': 4,
 'coronavirus': 5}

In [20]:
df.topic.unique()

array(['gun-control', 'marriage-equality', 'vaccines',
       'black lives matter', 'islam', 'coronavirus'], dtype=object)

In [21]:
#df.category = df['category'].map(label_dict)
df.topic = df['topic'].map(label_dict)

<ipython-input-21-2e2aa07ffc29>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.topic = df['topic'].map(label_dict)


In [22]:
set(df.topic)

{0, 1, 2, 3, 4, 5}

In [23]:
df

text  topic
1     "We have one beautiful law," Trump recently sa...      0
4     [Black Lives Matter] is essentially a non-fals...      1
5     [Democrats employ] their full arsenal to deleg...      2
6     [Newsoms's] obsession with masks has created a...      2
7     [Newsoms's] onslaught of propaganda ignores co...      2
...                                                 ...    ...
3666  You may remember that hours after America was ...      4
3667  You may remember that NBC journalist Nancy Sny...      2
3668  You need to keep a close eye on what your scho...      1
3669  You’ve heard of Jim Crow and Southern Segregat...      1
3670  Young female athletes’ dreams and accomplishme...      1

[1866 rows x 2 columns]

In [24]:
from sklearn.model_selection import train_test_split

In [25]:
X_train, X_val, y_train, y_val = train_test_split(df.index.values,
                                                  #df.category.values,
                                                  df.topic.values,
                                                  test_size=0.15,
                                                  random_state=42,
                                                  stratify=df.topic.values)
                                                  #stratify=df.category.values)

In [26]:
df.head()

text  topic
1  "We have one beautiful law," Trump recently sa...      0
4  [Black Lives Matter] is essentially a non-fals...      1
5  [Democrats employ] their full arsenal to deleg...      2
6  [Newsoms's] obsession with masks has created a...      2
7  [Newsoms's] onslaught of propaganda ignores co...      2

In [27]:
len(df)

1866

In [28]:
df['data_type'] = ['not_set']*df.shape[0]

<ipython-input-28-6709a8c15703>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['data_type'] = ['not_set']*df.shape[0]


In [29]:
df

text  topic data_type
1     "We have one beautiful law," Trump recently sa...      0   not_set
4     [Black Lives Matter] is essentially a non-fals...      1   not_set
5     [Democrats employ] their full arsenal to deleg...      2   not_set
6     [Newsoms's] obsession with masks has created a...      2   not_set
7     [Newsoms's] onslaught of propaganda ignores co...      2   not_set
...                                                 ...    ...       ...
3666  You may remember that hours after America was ...      4   not_set
3667  You may remember that NBC journalist Nancy Sny...      2   not_set
3668  You need to keep a close eye on what your scho...      1   not_set
3669  You’ve heard of Jim Crow and Southern Segregat...      1   not_set
3670  Young female athletes’ dreams and accomplishme...      1   not_set

[1866 rows x 3 columns]

In [30]:
df.loc[X_train, 'data_type'] = 'train'
df.loc[X_val, 'data_type'] = 'val'

In [31]:
df

text  topic data_type
1     "We have one beautiful law," Trump recently sa...      0     train
4     [Black Lives Matter] is essentially a non-fals...      1     train
5     [Democrats employ] their full arsenal to deleg...      2       val
6     [Newsoms's] obsession with masks has created a...      2     train
7     [Newsoms's] onslaught of propaganda ignores co...      2     train
...                                                 ...    ...       ...
3666  You may remember that hours after America was ...      4     train
3667  You may remember that NBC journalist Nancy Sny...      2     train
3668  You need to keep a close eye on what your scho...      1     train
3669  You’ve heard of Jim Crow and Southern Segregat...      1     train
3670  Young female athletes’ dreams and accomplishme...      1     train

[1866 rows x 3 columns]

In [32]:
df.groupby(['topic', 'data_type']).count()

text
topic data_type      
0     train       284
      val          50
1     train       295
      val          52
2     train       358
      val          63
3     train       370
      val          66
4     train       176
      val          31
5     train       103
      val          18

In [33]:
!pip install transformers

In [34]:
from transformers import BertTokenizer
from torch.utils.data import TensorDataset

In [35]:
tokenizer = BertTokenizer.from_pretrained(
    'bert-base-uncased', #bert-base-uncased using small bert model for simple data , bert-large-uncased fo large data
    do_lower_case=True
)

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:88: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


tokenizer_config.json:   0%|          | 0.00/28.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

In [36]:
df.head()

text  topic data_type
1  "We have one beautiful law," Trump recently sa...      0     train
4  [Black Lives Matter] is essentially a non-fals...      1     train
5  [Democrats employ] their full arsenal to deleg...      2       val
6  [Newsoms's] obsession with masks has created a...      2     train
7  [Newsoms's] onslaught of propaganda ignores co...      2     train

In [37]:
encoded_data_train = tokenizer.batch_encode_plus(

    df[df.data_type=='train'].text.values,
    add_special_tokens=True,
    return_attention_mask=True,
    pad_to_max_length=True,
    max_length=256,
    return_tensors='pt'
)

encoded_data_val = tokenizer.batch_encode_plus(
    df[df.data_type=='val'].text.values,
    add_special_tokens=True,
    return_attention_mask=True,
    pad_to_max_length=True,
    max_length=256,
    return_tensors='pt'
)

input_ids_train = encoded_data_train['input_ids']
attention_masks_train = encoded_data_train['attention_mask']
#labels_train = torch.tensor(df[df.data_type=='train'].category.values)
labels_train = torch.tensor(df[df.data_type=='train'].topic.values)

input_ids_val = encoded_data_val['input_ids']
attention_masks_val = encoded_data_val['attention_mask']
#labels_val = torch.tensor(df[df.data_type=='val'].category.values)
labels_val = torch.tensor(df[df.data_type=='val'].topic.values)

Truncation was not explicitly activated but `max_length` is provided a specific value, please use `truncation=True` to explicitly truncate examples to max length. Defaulting to 'longest_first' truncation strategy. If you encode pairs of sequences (GLUE-style) with the tokenizer you can select this strategy more precisely by providing a specific strategy to `truncation`.
/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py:2614: FutureWarning: The `pad_to_max_length` argument is deprecated and will be removed in a future version, use `padding=True` or `padding='longest'` to pad to the longest sequence in the batch, or use `padding='max_length'` to pad to a max length. In this case, you can give a specific length with `max_length` (e.g. `max_length=45`) or leave max_length to None to pad to the maximal input size of the model (e.g. 512 for Bert).
  warnings.warn(


In [38]:
input_ids_train

tensor([[ 101, 1000, 2057,  ...,    0,    0,    0],
        [ 101, 1031, 2304,  ...,    0,    0,    0],
        [ 101, 1031, 2739,  ...,    0,    0,    0],
        ...,
        [ 101, 2017, 2342,  ...,    0,    0,    0],
        [ 101, 2017, 1521,  ...,    0,    0,    0],
        [ 101, 2402, 2931,  ...,    0,    0,    0]])

In [39]:
#TensorDataset create a single variable which stores info of inputids , attentionmsk, labels
dataset_train = TensorDataset(input_ids_train,
                              attention_masks_train,
                              labels_train)

dataset_val = TensorDataset(input_ids_val,
                            attention_masks_val,
                           labels_val)

In [41]:
dataset_train.tensors

(tensor([[ 101, 1000, 2057,  ...,    0,    0,    0],
         [ 101, 1031, 2304,  ...,    0,    0,    0],
         [ 101, 1031, 2739,  ...,    0,    0,    0],
         ...,
         [ 101, 2017, 2342,  ...,    0,    0,    0],
         [ 101, 2017, 1521,  ...,    0,    0,    0],
         [ 101, 2402, 2931,  ...,    0,    0,    0]]),
 tensor([[1, 1, 1,  ..., 0, 0, 0],
         [1, 1, 1,  ..., 0, 0, 0],
         [1, 1, 1,  ..., 0, 0, 0],
         ...,
         [1, 1, 1,  ..., 0, 0, 0],
         [1, 1, 1,  ..., 0, 0, 0],
         [1, 1, 1,  ..., 0, 0, 0]]),
 tensor([0, 1, 2,  ..., 1, 1, 1]))

In [ ]:
# now we tokenize whole data now we set up model for classification

In [42]:
from transformers import BertForSequenceClassification

In [43]:
model = BertForSequenceClassification.from_pretrained(
                                      'bert-base-uncased',
                                      num_labels = len(label_dict),#5
                                      output_attentions = False,
                                      output_hidden_states = False
                                     )

model.safetensors:   0%|          | 0.00/440M [00:00<?, ?B/s]

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


In [44]:
label_dict

{'gun-control': 0,
 'marriage-equality': 1,
 'vaccines': 2,
 'black lives matter': 3,
 'islam': 4,
 'coronavirus': 5}

In [ ]:
# to load the data we require data loader

In [45]:
from torch.utils.data import DataLoader, RandomSampler, SequentialSampler

In [46]:
batch_size = 4

dataloader_train = DataLoader(
    dataset_train,
    sampler=RandomSampler(dataset_train),
    batch_size=batch_size
)

dataloader_val = DataLoader(
    dataset_val,
    sampler=RandomSampler(dataset_val),
    batch_size=32
)

In [47]:
from transformers import AdamW, get_linear_schedule_with_warmup

In [48]:
optimizer = AdamW(
    model.parameters(),
    lr = 1e-5,
    eps = 1e-8
)

/usr/local/lib/python3.10/dist-packages/transformers/optimization.py:411: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(


In [49]:
epochs = 3

scheduler = get_linear_schedule_with_warmup(
    optimizer,
    num_warmup_steps=0,
    num_training_steps = len(dataloader_train)*epochs
)

In [50]:
import numpy as np
from sklearn.metrics import f1_score

In [51]:
def f1_score_func(preds, labels):
    preds_flat = np.argmax(preds, axis=1).flatten()
    labels_flat = labels.flatten()
    return f1_score(labels_flat, preds_flat, average = 'weighted')

In [52]:
def accuracy_per_class(preds, labels):
    label_dict_inverse = {v: k for k, v in label_dict.items()}

    preds_flat = np.argmax(preds, axis=1).flatten()
    labels_flat = labels.flatten()

    for label in np.unique(labels_flat):
        y_preds = preds_flat[labels_flat==label]
        y_true = labels_flat[labels_flat==label]
        print(f'Class: {label_dict_inverse[label]}')
        print(f'Accuracy:{len(y_preds[y_preds==label])}/{len(y_true)}\n')

In [53]:
import random

seed_val = 17
random.seed(seed_val)
np.random.seed(seed_val)
torch.manual_seed(seed_val)
torch.cuda.manual_seed_all(seed_val)

In [54]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model.to(device)
print(device)

cuda


In [55]:
def evaluate(dataloader_val):

    model.eval()

    loss_val_total = 0
    predictions, true_vals = [], []

    for batch in tqdm(dataloader_val):

        batch = tuple(b.to(device) for b in batch)

        inputs = {'input_ids':      batch[0],
                  'attention_mask': batch[1],
                  'labels':         batch[2],
                 }

        with torch.no_grad():
            outputs = model(**inputs)

        loss = outputs[0]
        logits = outputs[1]
        loss_val_total += loss.item()

        logits = logits.detach().cpu().numpy()
        label_ids = inputs['labels'].cpu().numpy()
        predictions.append(logits)
        true_vals.append(label_ids)

    loss_val_avg = loss_val_total/len(dataloader_val)

    predictions = np.concatenate(predictions, axis=0)
    true_vals = np.concatenate(true_vals, axis=0)

    return loss_val_avg, predictions, true_vals

In [56]:
for epoch in tqdm(range(1, epochs+1)):
    model.train() #forward propagation
    loss_train_total = 0

    progress_bar = tqdm(dataloader_train,
                        desc='Epoch {:1d}'.format(epoch),
                        leave=False,
                        disable=False)

    for batch in progress_bar:
        model.zero_grad()
        batch = tuple(b.to(device) for b in batch)
        inputs = {
            'input_ids': batch[0],
            'attention_mask': batch[1],
            'labels': batch[2]
        }

        outputs = model(**inputs)
        loss = outputs[0]
        loss_train_total +=loss.item()
        loss.backward() #backwardprop

        torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)

        optimizer.step()
        scheduler.step()

        progress_bar.set_postfix({'training_loss': '{:.3f}'.format(loss.item()/len(batch))})

    torch.save(model, f'BERT_ft_Epoch{epoch}.model')

    tqdm.write(f'\nEpoch {epoch}')

    loss_train_avg = loss_train_total/len(dataloader_train)
    tqdm.write(f'Training loss: {loss_train_avg}')

    val_loss, predictions, true_vals = evaluate(dataloader_val)
    val_f1 = f1_score_func(predictions, true_vals)
    tqdm.write(f'Validation loss: {val_loss}')
    tqdm.write(f'F1 Score (weighted): {val_f1}')


  0%|          | 0/3 [00:00<?, ?it/s]

Epoch 1:   0%|          | 0/397 [00:00<?, ?it/s]


Epoch 1
Training loss: 1.3812902200432209


  0%|          | 0/9 [00:00<?, ?it/s]

Validation loss: 1.072754402955373
F1 Score (weighted): 0.5851387664378473


Epoch 2:   0%|          | 0/397 [00:00<?, ?it/s]


Epoch 2
Training loss: 0.9130801763807797


  0%|          | 0/9 [00:00<?, ?it/s]

Validation loss: 0.9741403592957391
F1 Score (weighted): 0.6106553419520134


Epoch 3:   0%|          | 0/397 [00:00<?, ?it/s]


Epoch 3
Training loss: 0.7197244961743691


  0%|          | 0/9 [00:00<?, ?it/s]

Validation loss: 0.9736646413803101
F1 Score (weighted): 0.6118644275892176


In [ ]:
## EVALUTION

In [57]:
import torch

In [95]:
headline = "“Mike Pence and the task force have done a great job,” Trump said during a visit to a mask factory in Arizona."

In [96]:
from transformers import BertTokenizer

In [97]:
tokenizer = BertTokenizer.from_pretrained(
    'bert-base-uncased', #bert-base-uncased using small bert model for simple data , bert-large-uncased fo large data
    do_lower_case=True
)

In [98]:
device = torch.device('cpu')

In [99]:
print(device)

cpu


In [100]:
encoded_headline = tokenizer(headline, return_tensors = 'pt')

In [101]:
encoded_headline

{'input_ids': tensor([[ 101, 1523, 3505, 7279, 3401, 1998, 1996, 4708, 2486, 2031, 2589, 1037,
         2307, 3105, 1010, 1524, 8398, 2056, 2076, 1037, 3942, 2000, 1037, 7308,
         4713, 1999, 5334, 1012,  102]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1]])}

In [102]:
input_ids = encoded_headline['input_ids'].to(device)
attention_msk = encoded_headline['attention_mask'].to(device)

In [103]:
path = '/content/BERT_ft_Epoch3.model'
model = torch.load(path, map_location = torch.device('cpu'))

In [104]:
model

BertForSequenceClassification(
  (bert): BertModel(
    (embeddings): BertEmbeddings(
      (word_embeddings): Embedding(30522, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (token_type_embeddings): Embedding(2, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (encoder): BertEncoder(
      (layer): ModuleList(
        (0-11): 12 x BertLayer(
          (attention): BertAttention(
            (self): BertSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): BertSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
              (LayerNorm): LayerNorm((768,), eps=1e-12,

In [105]:
model_output = model(input_ids,attention_msk)

In [106]:
model_output

SequenceClassifierOutput(loss=None, logits=tensor([[ 0.5624,  0.0206,  0.6418,  0.0966, -0.6448,  0.0117]],
       grad_fn=<AddmmBackward0>), hidden_states=None, attentions=None)

In [107]:
model_output_tensor = torch.tensor(model_output.logits)

<ipython-input-107-d2b33ccd89fe>:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  model_output_tensor = torch.tensor(model_output.logits)


In [108]:
model_output_tensor

tensor([[ 0.5624,  0.0206,  0.6418,  0.0966, -0.6448,  0.0117]])

In [109]:
model_output_tensor_categoryIndex = int(torch.argmax(model_output_tensor))

In [110]:
model_output_tensor_categoryIndex

2

In [111]:
classes ={0: 'gun-control', 1: 'marriage-equality', 2: 'vaccines', 3: 'black lives matter', 4: 'islam', 5: 'coronavirus'}

In [112]:
classes[model_output_tensor_categoryIndex]

'vaccines'